### ISSUE TITLE
Add placeholders to model about service units

### ISSUE THREAD

**Issue by alagane** [petalslink/petals-esb-deployer#7]
As a user
I want to be able to add placeholders to service units definition on the model
So I can model service units with placeholders

**Comment by cdeneux** [comment]
Default placeholder value can be defined at service unit definition in service unit model.
These default values can be overridden at service unit instance level using placeholder instance definition referencing an existing placeholder definition at service unit level.

**Comment by cdeneux** [comment]
Placeholder definition has been added to the model.
**It remains to do**: add a validation about the unique value of a placeholder for a component on a container.

**Comment by cdeneux** [comment]
Validation about the unique value of a placeholder for a component on a container was added by the previous commit.
